### ISSUE TITLE
oemof.db version

### ISSUE THREAD

**Issue by gplssm** [openego/ego.io#41]
I figured out issues with oemof.db v0.0.5: using this version results in an error similar to "package oemof is not installed". Do you run in the same error  @mariusves @ulfmueller @IlkaCu @wolfbunke @nesnoj @birgits @BartelsJ ?
In Ding0 we use v0.0.4 of oemof.db which works fine. Woulf someone of you mind to change the dependency of oemof.db in ego.io to v0.0.4?

**Comment by wolfbunke** [comment]
I had the same issue by installing ding0 and eDisGo two days ago for eGo and updated the version to `oemof.db==0.0.6.dev0` but I am not sure if this runs properly because I have still other package and version problems like networkx and others between eDisGo and eTraGo. If v0.0.4 works I am fine with it.

**Comment by mariusves** [comment]
I never had that specific error, have you tried the new db connection from #16 ? It doesn't need oemof.db anymore...

**Comment by gplssm** [comment]
I haven't tried it myself but @nesnoj did. He discovered some issues which he'll report soon. If we can resolve them quickly this issue can be neglected and closed.

**Comment by BartelsJ** [comment]
I just updated oemof.db to v0.0.5 and tried it - but I did not run into that error. But let's see the issues of @nesnoj.

**Comment by nesnoj** [comment]
New DB connection was merged into `dev` #16, should be resolved.
