### ISSUE TITLE
Include sqlacodegen in dependencies

### ISSUE THREAD

**Issue by gplssm** [openego/ego.io#43]
I'm heading towards release v0.3.0 and stumble for the first time upon the _sqlacodegen process_. As far as I understood we use the package sqlacodegen from PyPI. Thus, I ask myself why don't we include it in the dependencies?

Any opinion or hints? @nesnoj @MGlauer @IlkaCu @ulfmueller

**Comment by nesnoj** [comment]
I did not add the package since a assumed that a "normal" user
1. wants to access the data (from eDisGo, .. etc.) instead of creating table defs and
2. the required direct SQL access is limited to developers anyway.

But from my point of view it makes sense to add it now, since
1. the dialect will be available soon and
2. users can add tables to OEDB via OEP which are not automatically included in ego.io's defs.

So, feel free to add it..

**Comment by gplssm** [comment]
Done via 89ede0e
